### ISSUE TITLE
Golang api?

### ISSUE THREAD

**Issue by ReK2Fernandez** [keybase/keybase-chat-bot#38]
Are there plans for GO support to use the keybase api? (sorry if this is not the right place)

**Comment by maxtaco** [comment]
cc @mmaxim who has a library

**Comment by ReK2Fernandez** [comment]
@maxtaco thanks, @mmaxim looking forward to testing and using the library.

**Comment by mmaxim** [comment]
https://github.com/keybase/go-keybase-chat-bot
