### ISSUE TITLE
Create test scripts

### ISSUE THREAD

**Issue by malgorithms** [keybase/keybase-chat-bot#47]
We should introduce a `testbots` directory which has a series of test bot scripts. I think it makes sense to work like this:

`config.example.json` - a committed file with something like this in it (only JSON of course):

```
// copy this file to config.json and replace usernames and paper keys with real values, then you can run `npm run-script test-bots`
{
  "bots": {
    "alice1": {
      "username": "alice",
      "paperkey": "foo bar car..."
    },
    "alice2": {
      "username": "alice",
      "paperkey": "foo2 bar2 car2..."
    },
    "bob1": {
      "username": "bob",
      "paperkey": "foo3 bar3 car3..."
    }
  }
}
```

Then a series of individual test scripts:

* `count_to_10.js` - a script that inits `alice1` and `bob1` and has alice send 1 to bob, and bob replies with 2, and then alice replies with 3, etc., up to 10, then exits with a success. This can have alice watching for all new messages, and bob just watching the specific channel, so it will be testing both features.
* `alice_talks_to_self.js` - a script that has alice1 talk to alice2
* `attachments.js` - `alice1` checks the hash of a file, sends it to Bob. Bob receives file, saves it. Checks hash. (Requires attachments implemented first.)
* `cloned_device_chat.js` - I have no idea what _should_ happen if someone instantiates 2 bots with the exact same username and paperkey. If one of them posts a message does the other one get it inside of `watchForNewMessages` or not? But whatever the answer is, this script inits two `alice1` bots and checks the behavior
* `error_checks` - what happens if `alice1` sends a message that's too big? other errors?
* etc.

**Comment by maxtaco** [comment]
Related question: what is the CI story? We will need the keybase executable and also access to test accounts? Or should CI hit staging and can make new accounts when necessary?

**Comment by maxtaco** [comment]
I don't think it's much work. You can use an environment variable to pass through `KEYBASE_RUN_MODE=staging`.  And we can ship a static binary that runs on linux (or ask to install keybase via rpm or whatever, that's pretty easy...).  It shouldn't be more than 1-2 hours of work, and it might be really useful.

**Comment by malgorithms** [comment]
update: my oneshot PR includes such a script and configuration file, so let's mod this ticket to mean the introduction of something such as `yarn test` which runs all the tests in that directory and makes sure they all exit with success.

**Comment by malgorithms** [comment]
`yarn test` now works with 2 tests. we'll start expanding the tests.
