### ISSUE TITLE
Use Existing Service Mode

### ISSUE THREAD

**Issue by maxtaco** [keybase/keybase-chat-bot#48]
Chris asked for the opposite in #46, but I still want what's currently there. There's a case to be made that the bot should have an initialized level DB with lots of good locally cached data. This is better for *security* and *performance*.  I would personally want to run my bot this way.  So all that's needed is a mode where the existing library can plug into an already running service, in a well-known, non-temporary directory. Thanks!

**Comment by nathunsmitty** [comment]
Should this mode work as the bot currently does, where the service is running but a user is not logged in (and is logged in via oneshot mode)? Or should we handle the case where the service is running, a user is logged in, and wants to run a bot? Or should the bot handle both situations?

**Comment by maxtaco** [comment]
I would guess the latter scenario is more common.  This is lower-priority, BTW, I should have mentioned that.
