### ISSUE TITLE
Questioning this store/state/reducer model for this module

### ISSUE THREAD

**Issue by malgorithms** [keybase/keybase-chat-bot#55]
hi @thebearjew @nathunsmitty 

I've spent a bunch of time with the chatbot code yesterday and today, and I think I'm not sold on the introduction of the `store`. For one, the primary state of Keybase is managed in the actual keybase service itself, so any given Bot only needs to keep track of a few things (its username, working dir, etc.).

But more important, it seems like just for these few things, it's creating a lot of extra code and wrappers with little gain.

As a benefit, it's not like we ever need to rewind state, and I don't think tests will work on loaded or de-serialized state.

As an example of increased effort, I was just working on allowing one-shot mode.  I needed a bot to be aware of its working directory, a value it would generate for itself.  I'd imagine it would simply do something like this in its constructor and somehow save this info so it could be used later:

```javascript
workingDir = utils.randomTempDir()
```

this is easy to follow and only a line of work, exposing this information as needed.

Instead, I had to go into this `store/index.js` and edit the default initialState to add this:

```javacript
keybaseHomeDir: undefined,
```

Then I had to go to bot's init code and add this line:

```javacript
store.dispatch(actionPreInit(update))
```

Then I had to go to `store/actions.js` and create this special type:

```javacript
type PreInitProps = {|
|}
```
 
and an action:

```javacript
export const preInit = (props: PreInitProps): Action => ({
  type: 'PREINIT',
  payload: props,
})
```

and then I needed to go back to `store/index.js` and import and export it:

```javacript
import {actionPreinit} from './actions'
/* then later */
export {actionPreinit}
```

then back in `lib/base.js` I again to import it:

```javacript
import {actionPreinit} from '../store'
```

So I can finally "dispatch" this action to change this one value:

```javacript
    const update = {
      keybaseHomeDir: randomTempDir(),
    }
    store.dispatch(actionPreinit(update))
```

Also need to add this to `action/types.js`:

```javacript
export type PreinitAction = {|
  type: 'PREINIT',
  payload: {|
    keybaseHomeDir: string,
  |},
|}
```

and then redefine action to accept this new type:

```javacript
export type Action = InitAction | DeinitAction | PreinitAction
```

and then `store/types.js` need to handle the update type:

```javacript
+keybaseHomeDir: void | string,
```

Finally need to create a reducer in `store/reducer.js`:

```javacript
    case 'PREINIT': {
      return {
        ...state,
        keybaseHomeDir: action.payload.keybaseHomeDir
      }
    }
```

I'm guessing some of these steps could've been pared down, but it really does seem like even cutting it in half would leave an amazing amount of abstraction a contributor would have to page in.

As a final difficulty, it then leads to a lot of this kind of wrapping, just to get to the state: 

```javacript
const _somethingToDo = (store: Store) => {
  const somethingToDo: whatever = async () => {
    doSomething()
  }
  return somethingToDo
}
```
and then later exporting:

```javacript
somethingToDo: withStore(store)(_somethingToDo),
```

Again, this seems like a lot of function wrapping and returning, when in fact all along a `bot` could simply have access to its data.

I'm not convinced we're getting as much value from this as the effort.  And to be clear, I'm not saying we need to rewind this functional restructure right now, but just letting you know I'm thinking about it. I'll think about it more this weekend.

**Comment by nathunsmitty** [comment]
I noticed this too when working on oneshot: it is a lot of repetition across many files.

I think the biggest advantages we get from the functional structure are:
- better encapsulation of properties in the bot class
- ease of unit testing, as we don't have to create or initialize a bot when testing methods like `chat.read`

The disadvantages I've observed are:
- The structure does take time to learn
- Adding a feature requires touch a lot of files

The alternative approach I was playing around with before @thebearjew sold me on functional was a more traditional OO with a compositional twist: there was a `BaseBot` with standard `init`, `deinit`, and `status` methods and then each module was its own bot that inherited from that, e.g., `ChatBot`. The main `Bot` was a bot composed of these module-bots.

I wonder if a better solution would be to combine these two approaches, i.e., take an OO route for the main Bot, and have it handle initialization, etc. directly with methods but write modules such as `chat` in a more functional way? E.g., something like:

`bot.js`:
```js
class Bot {
  state: State

  constructor() {
    this.state = {
      /* initial state */
    }
    this.chat = chat(state)
  }

  async getCurrentUsernameAndDevicename() {
    const status = await keybaseExec(this.state.homeDir, ['status', '--json'], {json: true})
    if (status && status.Username && status.Device && status.Device.name) {
      return {username: status.Username, devicename: status.Device.name}
    } else {
      throw new Error('failed to get username + device name')
    }
  }

  async init(username, paperkey, options) {
    // create home dir
    await keybaseExec(homeDir, ['oneshot', '--username', username], {stdinBuffer: paperkey})
    const currentDPair = await this.getCurrentUsernameAndDevicename()
    if (currentDPair && currentDPair.username && currentDPair.devicename) {
      this.state.username = currentDPair.username
      this.state.devicename = currentDPair.devicename
      this.state.flags = options ? Boolean(options.verbose) : false
    }
  }
}
```

`chat.js`:
```js
const list: List = (state) => (async (options) => {
  const {tempDir} = state
  const res = await runApiCommand({method: 'list', options, tempDir})
  return res ? res.conversations || [] : []
})

...

const chat = (state) => ({
  list: state => list,
  ...
})

export default chat
```

**Comment by thebearjew** [comment]
@malgorithms @nathunsmitty You both raise great points. The I think the additional abstractions lead to more complexity for a new author. If Chris was having a hard time keeping tabs on files/functions then any newcomer would have significantly more trouble. Only realized recently that the current structure would be a major deterrent for someone looking to improve the keybase bot (not ideal or intended)! It seems that the functional structure over-optimized for isolation and added significant overhead. I Definitely think that balancing this out and leaning towards simplicity would be much better.

That said I actually thing reverting the functional state management would be a good decision to do immediately and change course to something that is agreeable. This would reduce any additional overhead moving forward. Perhaps now is a good time to continue with a discussion of architecture as @nathunsmitty began.

QQ: @malgorithms Intentions around functions + currying was to get the most out of testing. Now that we're discussing this, what does the ideal testing situation look like? I had envisioned a suite of unit tests looking at arguments, error handling, and return values for each method as well as a collection of "integration tests" where several bots are run simultaneously and communicate to each other (using a `devel` to `staging` `KEYBASE_RUN_MODE` environment) and the newly added temporary home directory.

**Comment by malgorithms** [comment]
good q aobut testing. 

In my opinion, the complexity here comes from the fact that the bulk of this software is outside the bot, with state managed heavily inside the keybase client/service that are spawned by the bot, and that outside software is changing *a lot*. 

For that reason, I think the ideal suite of tests should revolve around testing the end-to-end compatibility between the bot module and the `keybase` app, rather than simply the library itself. In other words: tests should be fully scripted bots that actually really work on the real network. Either the live site or staging.

Advantages:
- we don't need internal code abstractions designed for fake data loading, so the bot library can stay simple
- our tests pass only if the bot and keybase client software stay compatible, so we'll have breakages if CORE changes something something that would break our bot.
- our bot exports a handful of functions, so test coverage via scripts shouldn't be that hard.

The one example bot I introduced had `alice` and `bob` collaboratively test sending a message back and forth 10 times. This is a good first test, because it tests bots' abilities to initialize, to run simultaneously in the same script, to watch channels for new messages, and to reply with content based on the body of other messages.  It was very easy to write (great!) and yet tests so many things.

If we build a pretty good suite of such bots and have a single test script that tries all of them, then we'll be in very good shape.

I think for now we can run such a test script by hand on our own machines, then, with CORE's help a bit, we could set up something that runs and talks to staging and actually generates accounts on the fly. (say, with `bot.user.signup`) That would remove the need for the config file we can't check in, and allow the tests to run automatically. But that's an added bonus - for now we cna just do something like `yarn test` occasionally while working, and always before publishing.
