### ISSUE TITLE
pass logging dir param when spawning service

### ISSUE THREAD

**Issue by malgorithms** [keybase/keybase-chat-bot#88]
When running keybase normally the process gets args such as these:

```
keybase -d --log-file=/Users/chris/Library/Logs/keybase.service.log service
```

`-d` is debugging info; `--log-file` says where to write the logs. When users do a `keybase log send` this is what we get.

but our bot isn't logging at all, it's just writing to stderr and getting ignored. 

We should write to the bot's home directory a `keybase.service.log`.  And also use `-d` by default; we can talk about dropping that by default later when the bot is more stable.

**Comment by nathunsmitty** [comment]
how should we handle this if we're removing a bot's home directory (and thus presumably its logs) on `deinit`? or is that not something we should worry about?

**Comment by malgorithms** [comment]
I think it gets deleted then as part of the cleanup, which is fine. If someone wants to send us a log while the bot is running, it will work. otherwise the log is gone.
